# Generated by Django 6.0.2 on 2026-05-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fedramp_20x_ksi", "0004_compliancecontext_historicalcompliancecontext"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancecontext",
            name="regime",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="historicalcompliancecontext",
            name="regime",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
