# Generated by Django 6.0.2 on 2026-05-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fedramp_20x_ksi", "0005_compliancecontext_regime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="summary",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="historicalfinding",
            name="summary",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
