# Generated by Django 6.0.2 on 2026-07-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fedramp_20x_ksi", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="boundary",
            table="fedramp_20x_ksi__boundary",
        ),
        migrations.AlterModelTable(
            name="complianceartifact",
            table="fedramp_20x_ksi__compliance_artifact",
        ),
        migrations.AlterModelTable(
            name="compliancecontext",
            table="fedramp_20x_ksi__compliance_context",
        ),
        migrations.AlterModelTable(
            name="complianceexception",
            table="fedramp_20x_ksi__exception",
        ),
        migrations.AlterModelTable(
            name="evidence",
            table="fedramp_20x_ksi__evidence",
        ),
        migrations.AlterModelTable(
            name="finding",
            table="fedramp_20x_ksi__finding",
        ),
        migrations.AlterModelTable(
            name="ksicomponent",
            table="fedramp_20x_ksi__ksi_component",
        ),
        migrations.AlterModelTable(
            name="ksiindicator",
            table="fedramp_20x_ksi__ksi_indicator",
        ),
        migrations.AlterModelTable(
            name="ksisignal",
            table="fedramp_20x_ksi__ksi_signal",
        ),
        migrations.AlterModelTable(
            name="ksitheme",
            table="fedramp_20x_ksi__ksi_theme",
        ),
        migrations.AlterModelTable(
            name="ksivalidation",
            table="fedramp_20x_ksi__ksi_validation",
        ),
        migrations.AlterModelTable(
            name="ksiviolation",
            table="fedramp_20x_ksi__ksi_violation",
        ),
        migrations.AlterModelTable(
            name="vdrfinding",
            table="fedramp_20x_ksi__vdr_finding",
        ),
        migrations.AlterModelTable(
            name="vdrreport",
            table="fedramp_20x_ksi__vdr_report",
        ),
    ]
