# Generated by Django 6.0.2 on 2026-07-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fedramp_20x_ksi", "0003_alter_boundary_table_alter_complianceartifact_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compliancecontext",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceartifact",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceartifact",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcompliancecontext",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalcompliancecontext",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="ComplianceArtifact",
        ),
        migrations.DeleteModel(
            name="ComplianceContext",
        ),
        migrations.DeleteModel(
            name="HistoricalComplianceArtifact",
        ),
        migrations.DeleteModel(
            name="HistoricalComplianceContext",
        ),
    ]
