# Generated by Django 6.0.2 on 2026-07-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fedramp_20x_ksi", "0004_remove_compliancecontext_entity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complianceexception",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="evidence",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="finding",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalboundary",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalboundary",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceexception",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceexception",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalevidence",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalevidence",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalfinding",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalfinding",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="Boundary",
        ),
        migrations.DeleteModel(
            name="ComplianceException",
        ),
        migrations.DeleteModel(
            name="Evidence",
        ),
        migrations.DeleteModel(
            name="Finding",
        ),
        migrations.DeleteModel(
            name="HistoricalBoundary",
        ),
        migrations.DeleteModel(
            name="HistoricalComplianceException",
        ),
        migrations.DeleteModel(
            name="HistoricalEvidence",
        ),
        migrations.DeleteModel(
            name="HistoricalFinding",
        ),
    ]
